application: hands-for-you
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- deferred: on
- appstats: on

handlers:
- url: /static
  static_dir: static

- url: /_ah/queue/deferred
  login: admin
  script: google.appengine.ext.deferred.deferred.application

- url: /admin/.*
  login: admin
  script: urls.application

- url: /.*
  script: urls.application

libraries:
- name: webapp2
  version: 2.5.1
- name: jinja2
  version: 2.6